### PR TITLE
Potentially a wrong variable to print the debug message

### PR DESCRIPTION
**Pull request by javiquinte**
It should not be "debug" but "msg"

### CODE REVIEW

**Comment by merretbuurman** [comment]
Hi Javier! Thanks for spotting this one. Looks good. I think it should be merged into devel, not master - what do you think, @themiszamani ?
Have a nice weekend!

**Comment by themiszamani** [comment]
Dear @javiquinte and @merretbuurman 
Yes the PR should be against the devel instance.
@javiquinte  Could you please proceed with a new PR in devel?

**Comment by javiquinte** [comment]
Done in #87 !

**Comment by themiszamani** [comment]
it is the same as https://github.com/EUDAT-B2HANDLE/PYHANDLE/pull/87 in devel branch

**Pull request closed without merging**
