### PR TITLE
Add support for python 3.11

### PR DESCRIPTION
**Pull request by agelostsal**

### CODE REVIEW

**Comment by aquatix** [comment]
This installs fine with Python 3.11 on Debian 12 here, but I'd like to see a newer `requests` dependency; there is no reason to explicitly pin it on the ancient 2.28.1 - this hampers the rest of the project code that we use PYHANDLE in.

Can this be changed to `'requests>=2.28.1; python_version>="3.6.0"'` ? That works for us.

Thanks in advance, and nice work!

**Comment by aquatix** [comment]
In addition to `requests` 2.28.1 just being old, all versions between 2.3.0 and 2.30.0 have a security vulnerability: https://requests.readthedocs.io/en/latest/community/updates/#release-history

**Comment by agelostsal** [comment]
hello @aquatix , 
I think Python 3.6 can only handle requests 2.27.1.
All the other Python versions have gotten the latest requests version 2.31.0.

Cheers,
Angelos

**Comment by aquatix** [comment]
Hey @agelostsal those changes look great, thanks! Also thanks for not pinning the requests version to 2.31.0 but including newer ones too.

**Comment by dtroelofsprins** [comment]
I'm also running into issues with the requests being pinned at 2.28.1 in the current version of pyhandle (1.2.1). 
Happy to see that there is already work being done to make it 3.11 compatible including updating the requests requirement. 

Any idea when this will be merged and a new version of pyhandle will be released?

**Pull request merged**
