### PR TITLE
Update requests library to latest compatible version

### PR DESCRIPTION
**Pull request by agelostsal**

### CODE REVIEW

**Comment by themiszamani** [comment]
@agelostsal we would like to install >=2.23.

**Comment by aquatix** [comment]
It would be great if this could be released on pypi :)

**Comment by agelostsal** [comment]
@aquatix 

Hello Michiel. Do the version upgrades satisfy your use case, so we can move forward with closing this PR?

**Comment by aquatix** [comment]
Hey @agelostsal ,

Yes they do, everything seems to be installable again, thanks!

Only thing that I'm a bit concerned about, is that it is locked in this specific version again, so if some new (fix) release comes along, it will block the install.

For the moment though, this update works fine :)

**Pull request merged**
